pipeline:
  name: Boole
  identifier: Boole
  projectIdentifier: booline
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: boole
        identifier: boole
        description: ""
        type: FeatureFlag
        spec:
          execution:
            steps:
              - step:
                  type: FlagConfiguration
                  name: boole
                  identifier: boole
                  spec:
                    feature: Boolean
                    environment: Boole
                    instructions:
                      - identifier: SetFeatureFlagStateIdentifier
                        type: SetFeatureFlagState
                        spec:
                          state: "on"
                  timeout: 10m
